!!python/object:jmcomic.jm_option.JmOption
dir_tree: !!python/object:jmcomic.jm_option.DownloadDirTree
  Bd: /home/runner/work/18-comic-finder/downloadp/
  flag: Bd_Author_Title_Image

download_convert_image_suffix: null
download_image_then_decode: true
download_multi_thread_photo_batch_count: 10 # 一次多线程批量下载的数量，太多了禁漫服务器可能顶不住
download_multi_thread_photo_len_limit: 30
download_use_disk_cache: true

client_config:
  domain: null # null表明动态获取最新可用的禁漫域名
  retry_times: 5 # 请求失败时，重试的次数，配个正数就行，不配默认是5
  postman_type: cffi
  postman_type_list:
    - requests
    - requests_Session
    - cffi
    - cffi_Session
    - tls_client
  meta_data:
    proxies: null
    allow_redirects: true
    cookies: null
    headers:
      accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
      accept-language: zh-CN,zh;q=0.9
      authority: jmcomic1.rocks
      sec-ch-ua: '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"'
      sec-ch-ua-mobile: ?0
      sec-ch-ua-platform: '"Windows"'
      sec-fetch-dest: document
      sec-fetch-mode: navigate
      sec-fetch-site: none
      sec-fetch-user: ?1
      upgrade-insecure-requests: '1'
      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/109.0.0.0 Safari/537.36
