!!python/object:jmcomic.jm_option.JmOption
dir_tree: !!python/object:jmcomic.jm_option.DownloadDirTree
  Bd: /home/runner/work/jmcomic/download/
  flag: Bd_Author_Title_Image

disable_jm_module_debug: false
download_convert_image_suffix: null
download_image_then_decode: true
download_multi_thread_photo_batch_count: 15 # 一次多线程批量下载的数量，太多了禁漫服务器可能顶不住
download_multi_thread_photo_len_limit: 35
download_use_disk_cache: true

client_config:
  domain: null # null表明动态获取最新可用的禁漫域名
  retry_times: 5 # 请求失败时，重试的次数，配个正数就行，不配默认是5
  postman_type: cffi
  postman_type_list:
    - requests
    - requests_Session
    - cffi
    - cffi_Session
  meta_data:
    proxies: null
    allow_redirects: true
    cookies: null
