name: py

on:
  push:
    branches:
      - master
    paths:
      - 'py/jm.py'
      - '.github/workflows/py.yml'
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依赖包
        run: |
          pip install --upgrade pip
          pip install urllib3
          pip install jmcomic

      - name: 运行
        run: |
          python3 py/jm.py
          
      - name: 开始上传
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: finder-result
          # A file, directory or wildcard pattern that describes what to upload
          path: ./py
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 90